export type ProductCategory = "tops" | "bottoms" | "outerwear" | "swimwear";

export interface Product {
  id: string;
  name: string;
  category: ProductCategory;
  price: number;
  imageUrl: string;
  description: string;
  sizes: string[];
}

export const CATEGORY_LABELS: Record<ProductCategory, string> = {
  tops: "Tops",
  bottoms: "Pantalones y faldas",
  outerwear: "Abrigos",
  swimwear: "Trajes de baño",
};

export const CATEGORY_COLORS: Record<ProductCategory, string> = {
  tops: "bg-sky-50 text-sky-700",
  bottoms: "bg-indigo-50 text-indigo-700",
  outerwear: "bg-amber-50 text-amber-700",
  swimwear: "bg-pink-50 text-pink-700",
};

export const products: Product[] = [
  // ── Tops ──────────────────────────────────────────────────────────────────
  {
    id: "buzo-abotonado",
    name: "Buzo Abotonado",
    category: "tops",
    price: 89.99,
    imageUrl: "/garments/buzo-abotonado-lacoste.jpg",
    description: "Buzo abotonado de algodón premium con fit relaxed. Perfecto para el invierno.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "camisa-cuadros",
    name: "Camisa Cuadros Marrón",
    category: "tops",
    price: 69.99,
    imageUrl: "/garments/camisa-eron-cuadros-marron.jpg",
    description: "Camisa de cuadros en tonos marrón y beige. Corte regular, manga larga.",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "camisa-logos-rayas",
    name: "Camisa Logos y Rayas",
    category: "tops",
    price: 74.99,
    imageUrl: "/garments/camisa-eron-logos-rayas.jpg",
    description: "Camisa a rayas con logos bordados. Diseño moderno, corte slim.",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "camisa-full-cierre",
    name: "Camisa Full Cierre",
    category: "tops",
    price: 79.99,
    imageUrl: "/garments/camisa-full-cierre-lacoste.jpg",
    description: "Camisa con cierre completo, tejido liviano y transpirable. Ideal para el día.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "polo-azul",
    name: "Polo Azul",
    category: "tops",
    price: 59.99,
    imageUrl: "/garments/polo-azul-lacoste.jpg",
    description: "Polo clásico en azul Francia. Algodón piqué, cuello canalé, dos botones.",
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
  },
  {
    id: "polo-slim-navy",
    name: "Polo Slim Navy",
    category: "tops",
    price: 59.99,
    imageUrl: "/garments/polo-slim-navy-lacoste.jpg",
    description: "Polo slim fit en navy. Corte ajustado que estiliza la figura.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "polo-verde",
    name: "Polo Verde",
    category: "tops",
    price: 59.99,
    imageUrl: "/garments/polo-verde-lacoste.jpg",
    description: "Polo en verde bosque. Algodón piqué premium, fit regular.",
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
  },
  {
    id: "remera-campeon",
    name: "Remera Campeón Blanca",
    category: "tops",
    price: 39.99,
    imageUrl: "/garments/remera-campeon-blanco.jpg",
    description: "Remera blanca básica de algodón suave. El esencial que nunca falla.",
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
  },
  {
    id: "remera-detalle",
    name: "Remera Con Detalle",
    category: "tops",
    price: 49.99,
    imageUrl: "/garments/remera-detalle-lacoste.jpg",
    description: "Remera con detalles bordados en contraste. Algodón premium, corte regular.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "remera-icono-azul",
    name: "Remera Ícono Azul",
    category: "tops",
    price: 44.99,
    imageUrl: "/garments/remera-icono-azul.jpg",
    description: "Remera azul con logo ícono. Algodón 100%, fit holgado.",
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
  },
  {
    id: "remera-luma-azul",
    name: "Remera Luma Azul",
    category: "tops",
    price: 44.99,
    imageUrl: "/garments/remera-luma-azul.jpg",
    description: "Remera deportiva Luma en azul. Tela técnica transpirable, corte deportivo.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "remera-vuelta-al-mundo",
    name: "Remera Vuelta al Mundo",
    category: "tops",
    price: 49.99,
    imageUrl: "/garments/remera-vuelta-al-mundo.jpg",
    description: "Remera con estampado gráfico Vuelta al Mundo. 100% algodón.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "sweater-escote-v",
    name: "Sweater Escote V",
    category: "tops",
    price: 84.99,
    imageUrl: "/garments/sweater-escote-v-lacoste.jpg",
    description: "Sweater con escote en V y tejido suave. Ideal para looks de oficina o casual.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "sweater-jersey",
    name: "Sweater Jersey",
    category: "tops",
    price: 79.99,
    imageUrl: "/garments/sweater-jersey-lacoste.jpg",
    description: "Sweater de jersey suave, cuello redondo. Versátil y abrigado para el invierno.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "sweater-malabia",
    name: "Sweater Malabia Azul",
    category: "tops",
    price: 89.99,
    imageUrl: "/garments/sweater-malabia-azul.jpg",
    description: "Sweater Malabia en azul. Tejido grueso y abrigado, ideal para bajas temperaturas.",
    sizes: ["S", "M", "L", "XL"],
  },
  // ── Bottoms ───────────────────────────────────────────────────────────────
  {
    id: "jean-sakura",
    name: "Jean Sakura Azul",
    category: "bottoms",
    price: 99.99,
    imageUrl: "/garments/jean-sakura-azul.jpg",
    description: "Jean azul Sakura de tiro medio. Denim 100% algodón, corte slim.",
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "pantalon-fuji-cuadros",
    name: "Pantalón Fuji Cuadros",
    category: "bottoms",
    price: 89.99,
    imageUrl: "/garments/pantalon-fuji-cuadros-beige.jpg",
    description: "Pantalón Fuji a cuadros en beige. Tejido liviano, corte recto.",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "pantalon-interlock",
    name: "Pantalón Interlock",
    category: "bottoms",
    price: 79.99,
    imageUrl: "/garments/pantalon-interlock-lacoste.jpg",
    description: "Pantalón de interlock, tejido suave y elástico. Ideal para el día a día.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "pantalon-kioto",
    name: "Pantalón Kioto Marrón",
    category: "bottoms",
    price: 94.99,
    imageUrl: "/garments/pantalon-kioto-core-marron.jpg",
    description: "Pantalón Kioto Core en marrón. Corte recto con bolsillos laterales.",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "pantalon-relaxed",
    name: "Pantalón Relaxed",
    category: "bottoms",
    price: 84.99,
    imageUrl: "/garments/pantalon-relaxed-lacoste.jpg",
    description: "Pantalón relaxed fit. Corte amplio y cómodo, cintura elástica.",
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
  },
  {
    id: "pantalon-tirantes",
    name: "Pantalón con Tirantes",
    category: "bottoms",
    price: 109.99,
    imageUrl: "/garments/pantalon-tirantes-lacoste.jpg",
    description: "Pantalón con tirantes removibles. Look urbano y sofisticado.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "pollera-kai",
    name: "Pollera Kai Gris",
    category: "bottoms",
    price: 74.99,
    imageUrl: "/garments/pollera-kai-gris.jpg",
    description: "Pollera Kai en gris. Largo midi, corte recto y fluido.",
    sizes: ["XS", "S", "M", "L"],
  },
  // ── Outerwear ─────────────────────────────────────────────────────────────
  {
    id: "campera-canvas",
    name: "Campera Canvas Marrón",
    category: "outerwear",
    price: 159.99,
    imageUrl: "/garments/campera-daves-canvas-marron.jpg",
    description: "Campera Dave's en canvas marrón. Resistente al viento, bolsillos frontales.",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "campera-full-cierre",
    name: "Campera Full Cierre",
    category: "outerwear",
    price: 149.99,
    imageUrl: "/garments/campera-full-cierre-lacoste.jpg",
    description: "Campera con cierre completo y capucha. Abrigo liviano para entretiempo.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "campera-sakura",
    name: "Campera Sakura Azul",
    category: "outerwear",
    price: 169.99,
    imageUrl: "/garments/campera-sakura-azul.jpg",
    description: "Campera Sakura en azul marino. Acolchada, liviana y resistente al agua.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "chaleco-iron",
    name: "Chaleco Iron Marrón",
    category: "outerwear",
    price: 119.99,
    imageUrl: "/garments/chaleco-iron-marron.jpg",
    description: "Chaleco Iron en marrón. Acolchado liviano, sin mangas, cierre frontal.",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "piloto-sur",
    name: "Piloto Sur Verde",
    category: "outerwear",
    price: 179.99,
    imageUrl: "/garments/piloto-sur-verde.jpg",
    description: "Piloto Sur en verde oliva. Impermeable, con capucha desmontable.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "ropa1",
    name: "Prenda Especial",
    category: "tops",
    price: 54.99,
    imageUrl: "/garments/ropa1.webp",
    description: "Prenda de temporada. Diseño exclusivo, materiales de calidad.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  // ── Swimwear — Marea ──────────────────────────────────────────────────────
  {
    id: "entera-amberes-ivory-flora-rayas",
    name: "Entera Amberes Ivory Flora Rayas",
    category: "swimwear",
    price: 89.99,
    imageUrl: "/garments/marea/entera-amberes-ivory-flora-rayas.jpg",
    description: "Malla entera Amberes en ivory con estampado floral y rayas. Escote clásico, espalda cruzada.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "entera-anita",
    name: "Entera Anita",
    category: "swimwear",
    price: 84.99,
    imageUrl: "/garments/marea/entera-anita.jpg",
    description: "Malla entera Anita. Corte moderno, diseño minimalista y elegante.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "entera-arena-lisa",
    name: "Entera Arena Lisa",
    category: "swimwear",
    price: 79.99,
    imageUrl: "/garments/marea/entera-arena-lisa.jpg",
    description: "Malla entera Arena en color liso. Clásica y versátil para la playa o pileta.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "entera-dalia-jacquard",
    name: "Entera Dalia Jacquard",
    category: "swimwear",
    price: 94.99,
    imageUrl: "/garments/marea/entera-dalia-jacquard.jpg",
    description: "Malla entera Dalia en tejido jacquard. Textura premium, escote pronunciado.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "entera-dalia-mist-bloom",
    name: "Entera Dalia Mist Bloom",
    category: "swimwear",
    price: 94.99,
    imageUrl: "/garments/marea/entera-dalia-mist-bloom.jpg",
    description: "Malla entera Dalia en estampado Mist Bloom. Colores suaves, corte favorecedor.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "entera-dominica-i-ml-combinada",
    name: "Entera Dominica Manga Larga Combinada",
    category: "swimwear",
    price: 109.99,
    imageUrl: "/garments/marea/entera-dominica-i-ml-combinada.jpg",
    description: "Malla entera Dominica manga larga combinada. Diseño bicolor, protección UV.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "entera-dominica-ml-dos-cabos",
    name: "Entera Dominica Manga Larga Dos Cabos",
    category: "swimwear",
    price: 109.99,
    imageUrl: "/garments/marea/entera-dominica-ml-dos-cabos.jpg",
    description: "Malla entera Dominica manga larga Dos Cabos. Detalle de cabos en la espalda, protección UV.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "entera-french-biss-mist-bloom",
    name: "Entera French Biss Mist Bloom",
    category: "swimwear",
    price: 99.99,
    imageUrl: "/garments/marea/entera-french-biss-mist-bloom.jpg",
    description: "Malla entera French Biss en Mist Bloom. Escote cuadrado, breteles finos.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "entera-india-ii-less-paint-mood",
    name: "Entera India Less Paint Mood",
    category: "swimwear",
    price: 89.99,
    imageUrl: "/garments/marea/entera-india-ii-less-paint-mood.jpg",
    description: "Malla entera India II Less en estampado Paint Mood. Escote halter, espalda descubierta.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "entera-india-ii-less-velvet-wild",
    name: "Entera India Less Velvet Wild",
    category: "swimwear",
    price: 89.99,
    imageUrl: "/garments/marea/entera-india-ii-less-velvet-wild.jpg",
    description: "Malla entera India II Less en estampado Velvet Wild. Animal print sofisticado.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "entera-india-ii-micro-paint-mood",
    name: "Entera India Micro Paint Mood",
    category: "swimwear",
    price: 89.99,
    imageUrl: "/garments/marea/entera-india-ii-micro-paint-mood.jpg",
    description: "Malla entera India II Micro en estampado Paint Mood. Corte micro, actitud playera.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "entera-india-ii-micro-velvet-wild",
    name: "Entera India Micro Velvet Wild",
    category: "swimwear",
    price: 89.99,
    imageUrl: "/garments/marea/entera-india-ii-micro-velvet-wild.jpg",
    description: "Malla entera India II Micro en Velvet Wild. Tiro alto, corte moderno.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "entera-lucerna-jacquard-scale",
    name: "Entera Lucerna Jacquard Scale",
    category: "swimwear",
    price: 99.99,
    imageUrl: "/garments/marea/entera-lucerna-jacquard-scale.jpg",
    description: "Malla entera Lucerna en jacquard escamas. Textura única, corte clásico.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "entera-maceio-aqua-fleur",
    name: "Entera Maceio Aqua Fleur",
    category: "swimwear",
    price: 94.99,
    imageUrl: "/garments/marea/entera-maceio-aqua-fleur.jpg",
    description: "Malla entera Maceio en Aqua Fleur. Estampado floral acuático, escote V.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "entera-maceio-combinada-cebra",
    name: "Entera Maceio Combinada Cebra",
    category: "swimwear",
    price: 94.99,
    imageUrl: "/garments/marea/entera-maceio-combinada-cebra.jpg",
    description: "Malla entera Maceio combinada cebra. Print bicolor audaz, ideal para la playa.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "entera-maceio-ii-jacquard",
    name: "Entera Maceio II Jacquard",
    category: "swimwear",
    price: 99.99,
    imageUrl: "/garments/marea/entera-maceio-ii-jacquard.jpg",
    description: "Malla entera Maceio II en tejido jacquard. Segunda versión con escote renovado.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "entera-maceio-iii-jacquard-chain",
    name: "Entera Maceio III Jacquard Chain",
    category: "swimwear",
    price: 104.99,
    imageUrl: "/garments/marea/entera-maceio-iii-jacquard-chain.jpg",
    description: "Malla entera Maceio III en jacquard con cadenas. Detalle metálico integrado.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "entera-maceio-ivory-flora-rayas",
    name: "Entera Maceio Ivory Flora Rayas",
    category: "swimwear",
    price: 94.99,
    imageUrl: "/garments/marea/entera-maceio-ivory-flora-rayas.jpg",
    description: "Malla entera Maceio en ivory con flora y rayas. Femenina y sofisticada.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "entera-medellin-marea-signature",
    name: "Entera Medellín Marea Signature",
    category: "swimwear",
    price: 114.99,
    imageUrl: "/garments/marea/entera-medellin-marea-signature.jpg",
    description: "Malla entera Medellín de la línea Marea Signature. Diseño exclusivo de temporada.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "entera-munich-i-marea-signature",
    name: "Entera Munich Marea Signature",
    category: "swimwear",
    price: 114.99,
    imageUrl: "/garments/marea/entera-munich-i-marea-signature.jpg",
    description: "Malla entera Munich de la colección Marea Signature. Corte deportivo-elegante.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "entera-rafaela-jacquard-point",
    name: "Entera Rafaela Jacquard Point",
    category: "swimwear",
    price: 99.99,
    imageUrl: "/garments/marea/entera-rafaela-jacquard-point.jpg",
    description: "Malla entera Rafaela en jacquard puntillado. Escote corazón, corte favorecedor.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "entera-regina-combinada",
    name: "Entera Regina Combinada",
    category: "swimwear",
    price: 94.99,
    imageUrl: "/garments/marea/entera-regina-combinada.jpg",
    description: "Malla entera Regina combinada bicolor. Silueta estilizadora, breteles regulables.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "entera-regina-daisy-lavender",
    name: "Entera Regina Daisy Lavender",
    category: "swimwear",
    price: 94.99,
    imageUrl: "/garments/marea/entera-regina-daisy-lavender.jpg",
    description: "Malla entera Regina en Daisy Lavender. Flores delicadas sobre fondo lila.",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "entera-tulum-duo-jacquard",
    name: "Entera Tulum Duo Jacquard",
    category: "swimwear",
    price: 104.99,
    imageUrl: "/garments/marea/entera-tulum-duo-jacquard.jpg",
    description: "Malla entera Tulum Duo en jacquard doble textura. Look sofisticado para playa o pileta.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}
